import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import {AppRouterCacheProvider} from '@mui/material-nextjs/v13-appRouter';
import ClientProvider from "@/app/contexts/ClientProvider";
import {auth} from "@/app/api/auth/[...nextauth]/options";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await auth();

    return (
        <html lang="en">
        <body className={inter.className}>
        <ClientProvider session={session}>
            <AppRouterCacheProvider>
                {children}
            </AppRouterCacheProvider>
        </ClientProvider>
        </body>
        </html>
    );
}
